### ISSUE TITLE
Compile on raspberry with jessie

### ISSUE THREAD

**Issue by Roughtrade** [JvanKatwijk/wfm-rpi#1]
I got the following errors:
Makefile:490: recipe for target 'audiosink.o' failed
make: *** [audiosink.o] Error 1

if i use cmake i got this:
`[ 30%] Building CXX object CMakeFiles/wfm-rpi-dabstick-0.996.dir/src/main.cpp.o
In file included from /home/pi/wfm-rpi/./includes/gui.h:34:0,
                 from /home/pi/wfm-rpi/src/main.cpp:33:
/home/pi/wfm-rpi/ui_sdrgui.h:12:42: fatal error: Qt3Support/Q3MimeSourceFactory: Datei oder Verzeichnis nicht gefunden
 #include <Qt3Support/Q3MimeSourceFactory>
                                          ^
compilation terminated.
CMakeFiles/wfm-rpi-dabstick-0.996.dir/build.make:130: recipe for target 'CMakeFiles/wfm-rpi-dabstick-0.996.dir/src/main.cpp.o' failed
make[2]: *** [CMakeFiles/wfm-rpi-dabstick-0.996.dir/src/main.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/wfm-rpi-dabstick-0.996.dir/all' failed
make[1]: *** [CMakeFiles/wfm-rpi-dabstick-0.996.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by JvanKatwijk** [comment]
What if you use qmake-qt4/make? (after a make clean)

**Comment by Roughtrade** [comment]
Thanks a lot ! thats it
